---
language: perl
sudo: false
perl:
  - '5.22'
  - '5.20'
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
install:
  - cpanm -n -q --skip-satisfied --installdeps .
before_script:
  - coverage-setup
script: prove -lr t
after_success:
  - coverage-report
