---
language: perl
sudo: false
script: prove -lr t
install:
  - cpanm -n -q --skip-satisfied --installdeps .
perl:
  - '5.24'
  - '5.22'
  - '5.20'
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1
